kind: Route
apiVersion: route.openshift.io/v1
metadata:
  namespace: {{ocp-namespace}}
  name: spuerkeess-route
  labels:
    app: spuerkeess
spec:
  to:
    kind: Service
    name: spuerkeess-service
    weight: 256
  port:
    targetPort: 8080
  tls:
    termination: edge
  wildcardPolicy: None
---
